-- THIS FILE IS AUTO-GENERATED BY FORGE. DO NOT EDIT.
-- Ensure you have a user context setter function, e.g.:
-- CREATE OR REPLACE FUNCTION set_laforge_context(user_id UUID, tenant_id UUID, roles TEXT[], claims TEXT[])
-- RETURNS void AS $$
-- BEGIN
--   PERFORM set_config('laforge.user_id', user_id::text, false);
--   PERFORM set_config('laforge.tenant_id', tenant_id::text, false);
--   PERFORM set_config('laforge.roles', array_to_string(roles, ','), false);
--   PERFORM set_config('laforge.claims', array_to_string(claims, ','), false);
-- END;
-- $$ LANGUAGE plpgsql;

-- RLS Policies for users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS forge_delete_users ON users;
DROP POLICY IF EXISTS forge_update_users ON users;
DROP POLICY IF EXISTS forge_select_users ON users;
DROP POLICY IF EXISTS forge_insert_users ON users;
CREATE POLICY forge_insert_users ON users FOR INSERT WITH CHECK true;

-- RLS Policies for posts
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS forge_delete_posts ON posts;
DROP POLICY IF EXISTS forge_update_posts ON posts;
DROP POLICY IF EXISTS forge_select_posts ON posts;
DROP POLICY IF EXISTS forge_insert_posts ON posts;
CREATE POLICY forge_insert_posts ON posts FOR INSERT WITH CHECK true;
