
-- THIS FILE IS AUTO-GENERATED BY FORGE. DO NOT EDIT.
-- Ensure you have a user context setter function, e.g.:
-- CREATE OR REPLACE FUNCTION set_app_user(user_id UUID, tenant_id UUID, user_role TEXT)
-- RETURNS void AS $$
-- BEGIN
--   PERFORM set_config('app.user_id', user_id::text, false);
--   PERFORM set_config('app.tenant_id', tenant_id::text, false);
--   PERFORM set_config('app.user_role', user_role, false);
-- END;
-- $$ LANGUAGE plpgsql;


-- RLS Policies for users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS forge_delete_users ON users;
DROP POLICY IF EXISTS forge_update_users ON users;
DROP POLICY IF EXISTS forge_select_users ON users;
DROP POLICY IF EXISTS forge_insert_users ON users;
CREATE POLICY forge_insert_users ON users FOR INSERT WITH CHECK true;

-- RLS Policies for posts
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS forge_delete_posts ON posts;
DROP POLICY IF EXISTS forge_update_posts ON posts;
DROP POLICY IF EXISTS forge_select_posts ON posts;
DROP POLICY IF EXISTS forge_insert_posts ON posts;
CREATE POLICY forge_insert_posts ON posts FOR INSERT WITH CHECK true;
