
import { ModelDefinition } from '../ast/types.js';
import { GenerationResult } from '../ast/types.js';

function toPascalCase(str: string): string {
  return str.replace(/(?:^|-|_)(\w)/g, (_, c) => c.toUpperCase()).replace(/ /g, '');
}

export function generatePolicyGuards(models: ModelDefinition[]): GenerationResult {
  const guards = models.flatMap(model => {
    return Object.values(model.policies).map(policy => {
      const modelNamePascal = toPascalCase(model.name);
      const actionPascal = toPascalCase(policy.action);
      const functionName = `can${actionPascal}${modelNamePascal}`;
      
      return `
export const ${functionName}: PolicyHandler<typeof ${modelNamePascal}Schema> = ${policy.handlerSource};
`;
    });
  }).join('\n');

  const content = `
// THIS FILE IS AUTO-GENERATED BY FORGE. DO NOT EDIT.
import { ${models.map(m => `${toPascalCase(m.name)}Schema`).join(', ')} } from './zod';

type UserContext = {
  id: string;
  tenantId: string;
  role: string;
  roles?: string[];
  scopes?: string[];
  email?: string;
  claims?: Record<string, unknown>;
  [key: string]: any;
};
type PolicyHandler<T> = (ctx: { user: UserContext; record: T }) => boolean;

${guards}
`;

  // Note: This generated file isn't directly used by the domain layer generator,
  // which inlines the logic. However, it's useful for testing or direct use.
  // For simplicity in this implementation, we will inline logic in the domain generator.
  // So this file serves as a good reference.
  return {
    filePath: 'guards.ts',
    content,
  };
}
