
// THIS FILE IS AUTO-GENERATED BY FORGE. DO NOT EDIT.

import { FastifyInstance, FastifyRequest } from 'fastify';
import { Pool } from 'pg';
import { userDomain, postDomain, DomainContext, UserContext, AuditContext } from './domain';

// You must provide a database pool and a function to get the user from a request.
export interface ForgeAdapterOptions {
    dbPool: Pool;
    getUserFromRequest: (request: FastifyRequest) => UserContext | Promise<UserContext>;
    auditLogProvider?: AuditContext;
}

function createDefaultAuditContext(): AuditContext {
    return {
        record: (action, details) => {
            console.log(`[AUDIT] Action: ${action}, Details: ${JSON.stringify(details)}`);
        }
    };
}

export function createForgeRouter(options: ForgeAdapterOptions) {
    return async function forgeRouter(fastify: FastifyInstance) {
        
        const createDomainContext = async (request: FastifyRequest): Promise<DomainContext> => {
            const user = (request as any).user as UserContext;
            return {
                user,
                db: options.dbPool,
                audit: options.auditLogProvider || createDefaultAuditContext(),
            };
        };

        fastify.addHook('preHandler', async (request, reply) => {
            try {
                // Attach user to request for use in createDomainContext
                (request as any).user = await options.getUserFromRequest(request);
            } catch (error) {
                reply.code(401).send({ error: 'Unauthorized' });
            }
        });

        
    // --- Routes for User ---
    
    fastify.post('/user', async (request, reply) => {
        const ctx = await createDomainContext(request);
        const result = await userDomain.create(ctx, request.body as any);
        reply.code(201).send(result);
    });

    fastify.get('/user/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const result = await userDomain.findById(ctx, id);
        if (result) {
            reply.send(result);
        } else {
            reply.code(404).send({ error: 'User not found' });
        }
    });

    fastify.patch('/user/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const result = await userDomain.update(ctx, id, request.body as any);
         if (result) {
            reply.send(result);
        } else {
            reply.code(404).send({ error: 'User not found' });
        }
    });

    fastify.delete('/user/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const success = await userDomain.delete(ctx, id);
        if (success) {
            reply.code(204).send();
        } else {
            reply.code(404).send({ error: 'User not found' });
        }
    });

    // --- Routes for Post ---
    
    fastify.post('/post', async (request, reply) => {
        const ctx = await createDomainContext(request);
        const result = await postDomain.create(ctx, request.body as any);
        reply.code(201).send(result);
    });

    fastify.get('/post/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const result = await postDomain.findById(ctx, id);
        if (result) {
            reply.send(result);
        } else {
            reply.code(404).send({ error: 'Post not found' });
        }
    });

    fastify.patch('/post/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const result = await postDomain.update(ctx, id, request.body as any);
         if (result) {
            reply.send(result);
        } else {
            reply.code(404).send({ error: 'Post not found' });
        }
    });

    fastify.delete('/post/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const success = await postDomain.delete(ctx, id);
        if (success) {
            reply.code(204).send();
        } else {
            reply.code(404).send({ error: 'Post not found' });
        }
    });

    }
}
