
import { ModelDefinition } from '../ast/types.js';
import { GenerationResult } from '../ast/types.js';

function toPascalCase(str: string): string {
    return str.replace(/(?:^|-|_)(\w)/g, (_, c) => c.toUpperCase()).replace(/ /g, '');
}
function toCamelCase(str:string): string {
    const pascal = toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

export function generateFastifyAdapter(models: ModelDefinition[]): GenerationResult {
    const modelImports = models.map(m => `${toCamelCase(m.name)}Domain`).join(', ');

    const routes = models.map(model => {
        const namePascal = toPascalCase(model.name);
        const nameCamel = toCamelCase(model.name);
        const routeBase = `/${nameCamel}`;

        return `
    // --- Routes for ${namePascal} ---
    
    fastify.post('${routeBase}', async (request, reply) => {
        const ctx = await createDomainContext(request);
        const result = await ${nameCamel}Domain.create(ctx, request.body as any);
        reply.code(201).send(result);
    });

    fastify.get('${routeBase}/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const result = await ${nameCamel}Domain.findById(ctx, id);
        if (result) {
            reply.send(result);
        } else {
            reply.code(404).send({ error: '${namePascal} not found' });
        }
    });

    fastify.patch('${routeBase}/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const result = await ${nameCamel}Domain.update(ctx, id, request.body as any);
         if (result) {
            reply.send(result);
        } else {
            reply.code(404).send({ error: '${namePascal} not found' });
        }
    });

    fastify.delete('${routeBase}/:id', async (request, reply) => {
        const { id } = request.params as any;
        const ctx = await createDomainContext(request);
        const success = await ${nameCamel}Domain.delete(ctx, id);
        if (success) {
            reply.code(204).send();
        } else {
            reply.code(404).send({ error: '${namePascal} not found' });
        }
    });
`;
    }).join('');


    const content = `
// THIS FILE IS AUTO-GENERATED BY FORGE. DO NOT EDIT.

import { FastifyInstance, FastifyRequest } from 'fastify';
import { Pool } from 'pg';
import { ${modelImports}, DomainContext, UserContext, AuditContext } from './domain';

// You must provide a database pool and a function to get the user from a request.
export interface ForgeAdapterOptions {
    dbPool: Pool;
    getUserFromRequest: (request: FastifyRequest) => UserContext | Promise<UserContext>;
    auditLogProvider?: AuditContext;
}

function createDefaultAuditContext(): AuditContext {
    return {
        record: (action, details) => {
            console.log(\`[AUDIT] Action: \${action}, Details: \${JSON.stringify(details)}\`);
        }
    };
}

export function createForgeRouter(options: ForgeAdapterOptions) {
    return async function forgeRouter(fastify: FastifyInstance) {
        
        const createDomainContext = async (request: FastifyRequest): Promise<DomainContext> => {
            const user = (request as any).user as UserContext;
            return {
                user,
                db: options.dbPool,
                audit: options.auditLogProvider || createDefaultAuditContext(),
            };
        };

        fastify.addHook('preHandler', async (request, reply) => {
            try {
                // Attach user to request for use in createDomainContext
                (request as any).user = await options.getUserFromRequest(request);
            } catch (error) {
                reply.code(401).send({ error: 'Unauthorized' });
            }
        });

        ${routes}
    }
}
`;

    return {
        filePath: 'fastify.ts',
        content,
    };
}
